org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.caching=true

mod_version=0.3.0-beta.38
minecraft_version=26.2
minecraft_mapping=none
loader_version=0.19.3
fabric_api_version=0.152.1+26.2
minecraft_dependency=26.2
loader_dependency=>=0.19.3
malilib_version=0.29.4
malilib_dependency=ZCq1iE1J
litematica_version=0.28.5
litematica_dependency=Fhq3KCI8
syncmatica_version=0.3.20
syncmatica_dependency=POv0nHxV
sqlite_version=3.45.1.0
