pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.kikugie.dev/snapshots' }
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
    id 'dev.kikugie.stonecutter' version '0.9.7'
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT' apply false
    id 'net.fabricmc.fabric-loom-remap' version '1.17-SNAPSHOT' apply false
}

stonecutter {
    centralScript = 'build.gradle'
    create(rootProject) {
        version('1.21.7', '1.21.7')
        version('26.2', '26.2')
        vcsVersion = '1.21.7'
    }
}
