minecraft_version=1.21.7
minecraft_mapping=yarn
yarn_mappings=1.21.7+build.1
loader_version=0.16.13
fabric_api_version=0.129.0+1.21.7
minecraft_dependency=>=1.21.7 <=1.21.8
loader_dependency=>=0.16.9
malilib_version=0.25.7
malilib_dependency=2kC79eY3
litematica_version=0.23.7
litematica_dependency=GJMDd9Zq
syncmatica_version=0.3.15
syncmatica_dependency=x2GEse4M
sqlite_version=3.45.1.0
